os: osx
# addons:
#   homebrew:
#     packages:
#     - git
#     - curl
#     - jq
#     update: true
before_script:
  - curl -fsSL https://git.io/shellspec | sh -s -- --yes
language: bash
script:
  - shellspec --format d spec/unit/*.sh
