#!/usr/bin/env bash
echo "🧪 ShellSpec - KCOV Tests coverage report"
echo "🙈 Coverage"
KCOV_PATH="${HOME}/.local/bin"
REPORT_PATH=${PWD}/coverage
${KCOV_PATH}/kcov ${REPORT_PATH} ./src/*.sh
open ${REPORT_PATH}/index.html
